### ISSUE TITLE
npm WARN restful-blog-crud@1.0.0 No repository field.

### ISSUE THREAD

**Issue by toshcn** [HeskeyBaozi/RESTful-blog-server-demo#2]
npm install 后出现错误npm WARN restful-blog-crud@1.0.0 No repository field.
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node/bin/node', '/usr/bin/npm', 'run', 'db' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'predb', 'db', 'postdb' ]
5 info lifecycle restful-blog-crud@1.0.0~predb: restful-blog-crud@1.0.0
6 silly lifecycle restful-blog-crud@1.0.0~predb: no script for predb, continuing
7 info lifecycle restful-blog-crud@1.0.0~db: restful-blog-crud@1.0.0
8 verbose lifecycle restful-blog-crud@1.0.0~db: unsafe-perm in lifecycle true
9 verbose lifecycle restful-blog-crud@1.0.0~db: PATH: /usr/local/node/lib/node_modules/npm/bin/node-gyp-bin:/home/xiaohao/www/demo/blog-server/node_modules/.bin:/usr/local/node/bin:/home/xiaohao/bin:/home/xiaohao/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/xiaohao/go/bin:/home/xiaohao/gopath/bin:/usr/local/node/bin:/home/xiaohao/go/bin:/home/xiaohao/gopath/bin:/home/xiaohao/go/bin:/home/xiaohao/gopath/bin:/usr/local/node/bin
10 verbose lifecycle restful-blog-crud@1.0.0~db: CWD: /home/xiaohao/www/demo/blog-server
11 silly lifecycle restful-blog-crud@1.0.0~db: Args: [ '-c', 'mongod -dbpath ./data' ]
12 silly lifecycle restful-blog-crud@1.0.0~db: Returned: code: 100  signal: null
13 info lifecycle restful-blog-crud@1.0.0~db: Failed to exec db script
14 verbose stack Error: restful-blog-crud@1.0.0 db: `mongod -dbpath ./data`
14 verbose stack Exit status 100
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid restful-blog-crud@1.0.0
16 verbose cwd /home/xiaohao/www/demo/blog-server
17 error Linux 4.4.0-53-generic
18 error argv "/usr/local/node/bin/node" "/usr/bin/npm" "run" "db"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error restful-blog-crud@1.0.0 db: `mongod -dbpath ./data`
22 error Exit status 100
23 error Failed at the restful-blog-crud@1.0.0 db script 'mongod -dbpath ./data'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the restful-blog-crud package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     mongod -dbpath ./data
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs restful-blog-crud
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls restful-blog-crud
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by HeskeyBaozi** [comment]
运行mongod -dbpath ./data错误。
请删除./data目录下文件重试。注意此时相当于清空mongodb，需要再重新加入数据
